config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "rails/letter_opener"
  end

  mount Apipony::Engine => '/api/documentation'

  mount ActionCable.server => '/cable'

  get "/@:id" => 'users#show'
  patch "/@:id" => "users#update"
  delete "/@:id" => "users#destroy"
  post "/@:id/subscribe" => "users#subscribe"
  delete "/@:id/unsubscribe" => "users#unsubscribe"

  ############
  # CONCERNS #
  ############

  concern :reportable do
    post "report", on: :member
  end

  concern :commentable do
    post :comment, on: :member
    get :comments, on: :member
  end

  concern :replyable do
    resources :replies
  end

  concern :forumable do
    resources :topics do
      concerns :replyable
    end
  end

  ##################
  # RESTFUL ROUTES #
  ##################
  
  resources :favorites, only: [:create, :destroy] do
    get 'includes_image', on: :member
  end

  resources :conversations do
    resources :messages, only: [:index, :new, :create] do
      get 'by_time', on: :collection
    end
    post :read, on: :member
  end

  resources :tags do
    collection do
      get "suggest"
    end
    concerns :forumable
  end

  resources :commissions_dashboard, only: :index
  ##
  # Not really resourceful at all but whatever yolo
  resources :stripe, only: [] do
    collection do
      get :authorize
      get :callback
    end
  end
  
  resources :listings do
    get 'search', on: :collection
    get 'mine', on: :collection
    post 'confirm', on: :member
    post 'open', on: :member
    post 'close', on: :member

    resources :orders do
      post 'confirm', on: :member
      post 'accept', on: :member
      post 'purchase', on: :member
      post 'fill', on: :member
      post 'reject', on: :member
    end
  end

  get "/my_orders", to: "orders#mine"

  resources :tag_group_changes, only: [:show] do
  end

  resources :images do
    member do
      post "created"
    end

    collection do
      get "feed"
    end

    resources :tag_groups do
      resources :changes, only: [:index], controller: :tag_group_changes
    end

    concerns :reportable, :commentable
  end

  devise_for :users,
             path: "accounts",
             controllers: {
               sessions: "users/sessions"
             }

  resources :users, only: [:show, :edit, :update, :index] do
    get 'search', on: :collection
    ##
    # This is done so it's easier to see a users collections.
    # Meanwhile, creation and modification of collections is its own thing.
    member do
      put 'enable_twofactor'
      get 'verify_twofactor'
      get 'backup_twofactor'
      put 'confirm_twofactor'
      put 'disable_twofactor'
      get 'favorites'
      get 'creations'
      post 'subscribe'
      delete 'unsubscribe'
    end
  end

  resources :collections do
    get :mine, on: :collection
    ##
    # OK we get non-REST here
    resources :images, only: [:create, :destroy], controller: :collection_images do
      ##
      # An action which sees if an image already exists in the collection
      get "exists", on: :collection
    end

    resources :curatorships, except: [:index, :show]
    member do
      post "subscribe"
      delete "unsubscribe"
      ##
      # Refactor these out eventually
      post "add"
      delete "remove"
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'unread'
      post 'mark_all_read'
    end

    member do
      post 'read'
    end
  end

  resources :notes do
    collection do
      get 'feed'
    end
    concerns :replyable
  end

  ################
  # ADMIN ROUTES #
  ################

  namespace :admin do
    resources :images, only: [:index, :destroy] do
      post "absolve", on: :member
      collection do
        get 'live'
      end
    end
  end

  #################
  # BROWSE ROUTES #
  #################

  ########################
  # SINGLE ACTION ROUTES #
  ########################
  get 'settings', to: 'users#edit'
  post 'settings', to: 'users#update'

  #################
  # STATIC ROUTES #
  #################
  root to: "frontpage#index"
  get 'about', to: "static_stuff#about"
  get 'people', to: "static_stuff#people"
  get 'guidelines', to: "static_stuff#guidelines"
  get 'contact', to: "static_stuff#contact"
  get 'rules', to: "static_stuff#rules"
  get 'faq', to: "static_stuff#faq"
  get 'help', to: "static_stuff#help"
  get 'press', to: "static_stuff#press"
  get "terms_of_service", to: "static_stuff#terms_of_service"

  get 'search', to: "images#search"
end

app/models/collection.rb
# frozen_string_literal: true
##
# Collection is a way to organize images outside of the content within.
# An example of this might be all images that happened at a particular place
# in time, all images which have subjective quality in the opinion of a user
# (something like "beautiful"), or all the pages of a comic.
#
# It is an abstract class that uses STI to implement different functionality
# on child classes.
#
# == Relationships
# subscribers:: All users subscribed to this collection. Related via the join
#               table subscriptions.
# curators:: All the users who curate this collection. There's different levels
# images:: All images in this collection. Join table'd via collection_images.
#
# == Scopes
# favorites:: All collections of the Favorite variety.
class Collection < ActiveRecord::Base
  ################
  # ASSOCIATIONS #
  ################

  # Join table: User -> Collection
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user
  # Join table: User -> Collection
  has_many :curatorships
  has_many :curators, through: :curatorships, source: :user
  # Join table: Collection -> Images
  has_many :collection_images
  has_many :images,
           through: :collection_images

  ###############
  # VALIDATIONS #
  ###############

  validates :name, presence: true

  after_create :make_admins

  ##########
  # SCOPES #
  ##########

  ##
  # Get a list of collections ordered by how popular they are, in terms of
  # subscribers.
  def self.by_popularity(inter = 2.weeks.ago..Time.now, 
                         group_str: "collections.id")
    subs = Subscription.arel_table
    col = arel_table
    j = col.join(subs, Arel::Nodes::OuterJoin)
      .on(subs[:collection_id].eq(col[:id]), subs[:created_at].between(inter))
      .join_sources
    res = joins(j)
      .group(group_str)
      .order("COUNT(subscriptions) DESC")
  end

  ##
  # Get this scope, but with an additional column representing if this
  # collection contains the passed image
  # @param [Image] i the image
  def self.with_image_inclusion(i)
    ##
    # Using string interpolation is SQL is scary.
    # However, we force it to be an integer first, so it's less scary.
    select(%{
      collections.*, (collections.id IN
        (SELECT collections.id FROM collections
        INNER JOIN collection_images
          ON collection_images.collection_id = collections.id
        WHERE collection_images.image_id = #{i.id.to_i}))
        AS contains_image})
  end

  def self.without_image(i)
    where.not(id: i.collections)
  end

  def self.with_image(i)
    where(id: i.collections)
  end

  ####################
  # INSTANCE METHODS #
  ####################

  ##
  # Does a user curate this collection?
  # +u+:: the user
  # Example usage:
  #   collection.curated?(User.first) #=> true
  #   collection.curate?(User.last) #=> false
  def curated?(u)
    curators.include?(u)
  end

  protected

  def make_admins
    curatorships.update_all(level: 2)
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true
##
# A controller for actions relating to collections
class CollectionsController < ApplicationController
  before_action :ensure_user, except: [:index, :show]

  include Pundit

  ##
  # @collections: Collections belonging to the current user.
  def mine
    @collections = if t = params[:inspect_image]
                     img = Image.find(t)
                     current_user.collections.with_image_inclusion(img)
                   else
                     current_user.collections
                   end
    render 'index'
  end

  ##
  # "Browse collections" page.
  # @collections:: The collections displayed based on popularity or recency.
  def index
    image_scope = Image.for_content(content_pref)
    @collections = find_index_collections
      .includes(:images)
      .where(collection_images: {image_id: image_scope})
      .references(collection_images: :images)
      .paginate(page: page, per_page: per_page)
  end

  ##
  # Subscribes current_user to the collection with id in params[:id]
  # Requires login.
  # Redirects back afterwards.
  # If "redirect back" means nothing (IE, hitting the back button is impossible
  # since the user's first page in the session was this page), it redirects
  # to the homepage.
  def subscribe
    current_user.subscribe! Collection.find(params[:id])
    redirect_back fallback_location: root_path
  end

  ##
  # Unsubscribe from a collection
  # Member action
  def unsubscribe
    Subscription.where(collection_id: params[:id],
                       user_id: current_user.id)
      .first
      .try(:destroy)
    redirect_to Collection.find(params[:id])
  end

  ##
  # Show a collection, including all info and images within.
  # Sets the following varaibles:
  # @collection:: The collection being viewed
  # @curators:: the users who curate the collection
  # @images:: Images in the collection
  def show
    @collection = Collection.find(params[:id])
    @images = @collection.images
      .order("collection_images.created_at DESC")
      .paginate(page: page, per_page: per_page)
      .for_content(content_pref)
    @curators = @collection.curators
  end

  ##
  # Displays a page to create a new collection.
  # Requires login.
  # Sets the following variables:
  # @collection:: A new collection object for form-building.
  def new
    @collection = Collection.new
  end

  ##
  # POST to create a new collection
  # Redirects to the new action with errors in flash[:warning] on failure,
  # and to the created collection on success.
  def create
    c = Collection.new(collection_params)
    respond_to do |format|
      if c.save
        format.html { redirect_to collection_path(id: c.id), notice: I18n.t("notices.collection_created_successfully") }
      else
        format.html { redirect_to new_collection_path, warning: c.errors.full_messages.join(", ") }
      end
    end
  end

  ##
  # Edit a given collection.
  # @collection:: Collection being edited.
  def edit
    @collection = Collection.find(params[:id])
  end

  ##
  # Update a given collection.
  # @collection:: Collection being updated.
  def update
    @collection = Collection.find(params[:id])
    authorize @collection
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection }
        format.json { render :show }
      else
        format.html { render :edit, status: :unproccessible_entity }
        format.json { render @collection.errors, status: :unprocessible_entity }
      end
    end
  end

  ##
  # Delete a given collection.
  # @collection:: Collection being deleted.
  def destroy
    @collection = Collection.find(params[:id])
    authorize @collection
    @collection.destroy
    redirect_to root_path
  end

  protected

  ##
  # Convenience method that finds collections for the "Browse Collections" page.
  # Sorted either by upload date or by popularity.
  def find_index_collections
    case params['order']
    when "created_at"
      Collection.order(created_at: :desc)
    else
      Collection.by_popularity(group_str: "collections.id, images.id")
    end
  end

  ##
  # Parameters needed to create the collection.
  # name:: What to name this collection
  # description:: A short bit of info describing this collection.
  def collection_params
    params.require(:collection)
      .permit(:name, :description)
      .merge(curators: [current_user])
  end
end

app/views/collections/_form.html.erb
<div class="fields-page-container">

  <%= form_for @collection do |f| %>
    
    <div class="field-container">
      <%= f.label :name, t(".title"), class: "label input-empty", for: "new-collection-title" %>
      <%= f.text_field :name, id: "new-collection-title", class: "input", autocomplete: "off" %>
    </div>

    <div class="field-container">
      <%= f.label :name, t(".description"), class: "label input-empty", for: "new-collection-description" %>
      <%= f.text_area :description, class: "input", autocomplete: "off" %>
    </div>

    <%# You're going to be able to select the type of collections soon,
      for now we just use this %>
    <%= f.hidden_field :type, value: "Subjective" %>
    
    <%= f.submit t(".submit.#{action_name}"), id: "new-collection-submit", class: "btn btn-green btn-full-width" %>
  <% end %>
</div>

app/views/collections/_show_stub.html.erb
<div class="collection-preview">

  <%= link_to collection_path(collection) do %>
    <div class="collection-thumbnail">
      <%= image_tag(collection.images.first.try(:f, :medium) || 
        "empty-collection.svg") %>
    </div>

    <div class="collection-information">
      <p class="collection-title"><%= collection.name %>
      
      <% unless collection.description.empty? %>
        <p class="collection-description"><%= collection.description %>
      <% end %>
    </div>

  <% end %>

</div>

app/views/collections/edit.html.erb
<%- title t(".edit_collection") %>

<h3 class="generic-page-title"><%= t(".edit_collection") %></h3>

<%= render "form" %>

app/views/collections/index.html.erb
<%- title t(".browse_collections") %>

<%= render partial: "shared/browse_tabs" %>

<div class="collections-list-container">
  <%= render partial: "collections/show_stub", collection: @collections, as: :collection %>
</div>

<%= will_paginate @collections %>

app/views/collections/new.html.erb
<%- title t(".new_collection") %>

<h3 class="generic-page-title"><%= t(".new_collection") %></h3>

<%= render 'form' %>

app/views/collections/show.html.erb
<%- title @collection.name %>

<div class="collection-page-container">
  <div class="collection-page-header">
    <% cache ["info", @collection] do %>
      <%# Collection info %>
      <div class="collection-page-info-container">

        <%# Collection title %>
        <p class="collection-page-title"><%= @collection.name %>

        <%# Collection description %>
        <p class="collection-page-description"><%= @collection.description %>

        <%# Collection curators %>
        <p class="collection-page-curators"><%= t(".curated_by_html",
            curators_list: @collection.curators.collect { |curator| link_to(curator.name, curator) }.join(",").html_safe ) %>
      </div>
    <% end %>

    <% if policy(@collection).update? %>
      <%= link_to t(".edit"), edit_collection_path(@collection), class: "btn btn-minimal btn-minimal-with-padding" %>
    <% end %>
    
    <% if policy(@collection).destroy? %>
      <%= link_to t(".delete"), collection_path(@collection), method: :delete, class: "btn btn-minimal btn-minimal-red btn-minimal-with-padding" %>
    <% end %>

    <%# If the user is already subscribed to, or "Following", a collection,
      render the Unfollow button as active. If pressed, the Unfollow button is replaced
    and by the Follow button. %>
    <% if current_user.try(:subscribed_to?, @collection) %>

      <%= form_tag(unsubscribe_collection_path(@collection.id), "data-signed-in": "ajax", method: :delete, remote: true) do %>
        <%= button_tag id: "collection-unfollow", class: "btn btn-unfollow active" do %>
          <span class="btn-text-following"> <%= t(".following") %> </span>
          <span class="btn-text-unfollow"> <%= t(".unfollow") %> </span>
        <% end %>
      <% end %>

      <%= form_tag(subscribe_collection_path(@collection.id), "data-signed-in": "ajax", remote: true) do %>
        <%= button_tag t(".follow"), id: "collection-follow", class: "btn btn-follow inactive" %>
      <% end %>

      <%# If the user isn't subscribed to the collection, do the opposite. %>
    <% else %>

      <%= form_tag(unsubscribe_collection_path(@collection.id), "data-signed-in": "ajax", method: :delete, remote: true) do %>
        <%= button_tag id: "collection-unfollow", class: "btn btn-unfollow inactive" do %>
          <span class="btn-text-following"> <%= t(".following") %> </span>
          <span class="btn-text-unfollow"> <%= t(".unfollow") %> </span>
        <% end %>
      <% end %>

      <%= form_tag(subscribe_collection_path(@collection.id), "data-signed-in": "ajax", remote: true) do %>
        <%= button_tag t(".follow"), id: "collection-follow", class: "btn btn-follow active" %>
      <% end %>

    <% end %>
  </div>
  
  <% cache ["images", @collection] do %>
    <%# Render collection's images  %>
    <div class="collection-images-container">
      <%= render 'images/show_stub', images: @images %>
    </div>
  <% end %>
</div>