config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "rails/letter_opener"
  end

  mount Apipony::Engine => '/api/documentation'

  mount ActionCable.server => '/cable'

  get "/@:id" => 'users#show'
  patch "/@:id" => "users#update"
  delete "/@:id" => "users#destroy"
  post "/@:id/subscribe" => "users#subscribe"
  delete "/@:id/unsubscribe" => "users#unsubscribe"

  ############
  # CONCERNS #
  ############

  concern :reportable do
    post "report", on: :member
  end

  concern :commentable do
    post :comment, on: :member
    get :comments, on: :member
  end

  concern :replyable do
    resources :replies
  end

  concern :forumable do
    resources :topics do
      concerns :replyable
    end
  end

  ##################
  # RESTFUL ROUTES #
  ##################
  
  resources :favorites, only: [:create, :destroy] do
    get 'includes_image', on: :member
  end

  resources :conversations do
    resources :messages, only: [:index, :new, :create] do
      get 'by_time', on: :collection
    end
    post :read, on: :member
  end

  resources :tags do
    collection do
      get "suggest"
    end
    concerns :forumable
  end

  resources :commissions_dashboard, only: :index
  ##
  # Not really resourceful at all but whatever yolo
  resources :stripe, only: [] do
    collection do
      get :authorize
      get :callback
    end
  end
  
  resources :listings do
    get 'search', on: :collection
    get 'mine', on: :collection
    post 'confirm', on: :member
    post 'open', on: :member
    post 'close', on: :member

    resources :orders do
      post 'confirm', on: :member
      post 'accept', on: :member
      post 'purchase', on: :member
      post 'fill', on: :member
      post 'reject', on: :member
    end
  end

  get "/my_orders", to: "orders#mine"

  resources :tag_group_changes, only: [:show] do
  end

  resources :images do
    member do
      post "created"
    end

    collection do
      get "feed"
    end

    resources :tag_groups do
      resources :changes, only: [:index], controller: :tag_group_changes
    end

    concerns :reportable, :commentable
  end

  devise_for :users,
             path: "accounts",
             controllers: {
               sessions: "users/sessions"
             }

  resources :users, only: [:show, :edit, :update, :index] do
    get 'search', on: :collection
    ##
    # This is done so it's easier to see a users collections.
    # Meanwhile, creation and modification of collections is its own thing.
    member do
      put 'enable_twofactor'
      get 'verify_twofactor'
      get 'backup_twofactor'
      put 'confirm_twofactor'
      put 'disable_twofactor'
      get 'favorites'
      get 'creations'
      post 'subscribe'
      delete 'unsubscribe'
    end
  end

  resources :collections do
    get :mine, on: :collection
    ##
    # OK we get non-REST here
    resources :images, only: [:create, :destroy], controller: :collection_images do
      ##
      # An action which sees if an image already exists in the collection
      get "exists", on: :collection
    end

    resources :curatorships, except: [:index, :show]
    member do
      post "subscribe"
      delete "unsubscribe"
      ##
      # Refactor these out eventually
      post "add"
      delete "remove"
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'unread'
      post 'mark_all_read'
    end

    member do
      post 'read'
    end
  end

  resources :notes do
    collection do
      get 'feed'
    end
    concerns :replyable
  end

  ################
  # ADMIN ROUTES #
  ################

  namespace :admin do
    resources :images, only: [:index, :destroy] do
      post "absolve", on: :member
      collection do
        get 'live'
      end
    end
  end

  #################
  # BROWSE ROUTES #
  #################

  ########################
  # SINGLE ACTION ROUTES #
  ########################
  get 'settings', to: 'users#edit'
  post 'settings', to: 'users#update'

  #################
  # STATIC ROUTES #
  #################
  root to: "frontpage#index"
  get 'about', to: "static_stuff#about"
  get 'people', to: "static_stuff#people"
  get 'guidelines', to: "static_stuff#guidelines"
  get 'contact', to: "static_stuff#contact"
  get 'rules', to: "static_stuff#rules"
  get 'faq', to: "static_stuff#faq"
  get 'help', to: "static_stuff#help"
  get 'press', to: "static_stuff#press"
  get "terms_of_service", to: "static_stuff#terms_of_service"

  get 'search', to: "images#search"
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  # RELATIONS
  belongs_to :user, required: true

  has_many :listing_images,
    class_name: 'Listing::Image',
    inverse_of: :listing

  has_many :images, 
    through: :listing_images,
    class_name: "::Image"

  has_many :orders

  # VALIDATION
  validates :name,
    presence: true

  validates :description,
    presence: true


  # SCOPES
  scope :open, -> { where(open: true) }

  def self.with_average_prices
    listings = Listing.arel_table
    orders = Order.arel_table
    join = listings.join(orders, Arel::Nodes::OuterJoin)
      .on(orders[:listing_id].eq(listings[:id]))
      .join_sources
    self.joins(join)
      .group("listings.id")
      .select("listings.*, AVG(orders.final_price) AS average_price")
  end

  def completely_safe?
    ! (nsfw_gore? || nsfw_nudity? || nsfw_language? || nsfw_sexuality?)
  end


  def make_open!
    update(open: true)
  end

  def make_closed!
    update(open: false)
  end

  def closed?
    ! open?
  end
end

require_dependency 'listing/image'

app/models/listing/image.rb
class Listing
  class Image < ActiveRecord::Base
    belongs_to :image,
      class_name: "::Image"

    belongs_to :listing

    validates :image, presence: true

    validates :listing, presence: true

    validate :share_user

    protected

    def share_user
      unless image.creators.include? listing.user 
        errors.add(:image, "was not created by this user")
      end
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include Pundit

  before_action :ensure_user, except: [:index, :show]

  def mine
    @listings = current_user.listings
      .includes(:images)
      .order(created_at: :desc)
      .paginate(page: page, per_page: per_page)
    render 'index'
  end

  def index
    listings = Listing.all
      .with_average_prices
      .open
      .order(created_at: :desc)
      .paginate(page: page, per_page: per_page)
      .includes(:images)
    @listings = ListingsPresenter.new(listings)
  end

  def show
    @listing = Listing.find(params[:id])
    authorize @listing
  end

  def new
    @listing = Listing.new
  end

  def edit
    @listing = Listing.find(params[:id])
    authorize @listing
  end

  def update
    @listing = Listing.find(params[:id])
    authorize @listing
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing }
        format.json { render 'show' }
      else
        format.html { render 'edit', errors: @listing.errors }
        format.html do 
          render json: @listing.errors,
            status: :unprocessible_entity
        end
      end
    end
  end

  def create
    @listing = Listing.new(listing_params)
    authorize @listing
    respond_to do |format|
      if @listing.save
        format.json { render 'show' }
        format.html { redirect_to @listing }
      else
        format.html { render 'new' }
        format.json { render json: @listing.errors, status: 422 }
      end
    end
  end

  def open
    @listing = Listing.find(params[:id])
    authorize @listing
    begin
      ListingOpenService.new(@listing).perform
    rescue ListingOpenService::StripelessUserError
      redirect_to authorize_stripe_index,
        alert: "You need to connect to Stripe first."
      return
    end
    redirect_to @listing
  end

  def close
    @listing = Listing.find(params[:id])
    authorize @listing
    @listing.make_closed!
    redirect_to @listing
  end

  protected
  def listing_params
    params.require(:listing)
      .permit(:name,
              :description,
              :base_price,
              :quote_only,
              :nsfw_gore,
              :nsfw_language,
              :nsfw_sexuality,
              :nsfw_nudity,
              image_ids: [],
              options_attributes: [option_attributes],
              categories_attributes: [categories_attributes])
      .merge(user_id: current_user.id)
  end

  def option_attributes
    [:price,
      :_destroy,
      :name,
      :description,
      :id]
  end


  def categories_attributes
    [:price,
      :_destroy,
      :max_count,
      :free_count,
      :name,
      :description,
      :id]
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_category.html.erb
<li class="listing-category-show">
  <h2 class="padded-dark-header">
    <%= category.name.pluralize(category.max_count) %>
  </h2>
  <div class="markdown-description">
    <%= markdown_parse category.description %>
  </div>
  <div class="category-price">
    <div>Price</div>
    <div>
      <% if category.free_count > 0 %>
        <span>
          <strong><%= category.free_count %></strong> included, </span>
      <% end %>
      <strong><%= price category.price %></strong>
      <% if category.max_count > 1 %>
        <span>each (<strong><%= category.max_count %></strong> max)</span>
      <% end %>
    </div>
  </div>
</li>

app/views/listings/_form.html.erb
<%= form_for @listing, html: { :class => "listing-form" }  do |f| %>
  <h2>New Listing</h2>

  <div class="field-container">
    <%= f.label :name, :class => "label" %>
    <%= f.text_field :name, :class => "input"  %>
  </div>

  <div class="field-container">
    <%= f.label :description, :class => "label" %>
    <%= f.text_area :description, :class => "input" %>
  </div>

  <div class="listing-content-ratings">
    <h5>Content Allowed</h5>
    <p class="faded-warning">
      Never feel pressured into making Artwork you aren't comfortable with.
    </p>

    <div class="checkbox-field">
      <%= f.check_box :nsfw_gore %>
      <%= f.label :nsfw_gore %>
    </div>

    <div class="checkbox-field">
      <%= f.check_box :nsfw_language %>
      <%= f.label :nsfw_language %>
    </div>

    <div class="checkbox-field">
      <%= f.check_box :nsfw_nudity %>
      <%= f.label :nsfw_nudity %>
    </div>

    <div class="checkbox-field">
      <%= f.check_box :nsfw_sexuality %>
      <%= f.label :nsfw_sexuality %>
    </div>

  </div>


  <%= react_component "ListingForm", 
    render(file: "listings/show.json.jbuilder") %>
<% end %>

app/views/listings/_listing.html.erb
<li class="listings-list-item">
  <div class="listing-info">
    <h1><%= link_to listing.name, listing %></h1>

    <div class="listings-list-description">
      <%= markdown_parse listing.description %>
    </div>

    <% if listing.average_price %>
      <div class="listing-average-price">
        Average Price: 
        <%= price listing.average_price %>
      </div>
    <% end %>
  </div>

  <% unless listing.sample_images.empty? %>
    <ul class="image-gallery listing-image-gallery">
      <% listing.sample_images(8).each do |img| %>
        <li class="image-gallery-item gallery-item-small">
          <%= link_to img do %>
            <%= image_tag img.f(:medium) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/listings/_option.html.erb
<li class="options-item">
  <div class="options-header">
    <h3><%= option.name %></h3>
    <% unless @listing.quote_only? %>
      <% if option.price == 0 %> 
        <strong>Free</strong>
      <% else %>
        <strong><%= price option.price %></strong>
      <% end %>
    <% end %>
  </div>
  <div class="markdown-description">
    <%= markdown_parse option.description %>
  </div>
</li>

app/views/listings/index.html.erb
<%- title "Listings" %>

<%= render partial: "shared/browse_tabs" %>

<ul class="listings-list" class="flex-column">
  <%= render @listings %>
</ul>

<%= will_paginate @listings %>

app/views/listings/new.html.erb
<%= render 'form' %> 

app/views/listings/show.html.erb
<div id="show-listing">

  <div class="show-listing-header flex-column">
    <h1><%= @listing.name %></h1>
    <div class="listing-artist flex-row">
      <span>By</span>
      <%= image_tag @listing.user.avatar_img_thumb %>
      <%= link_to @listing.user.name, @listing.user %>
    </div>
  </div>

  <div class="markdown-area">
    <%= markdown_parse @listing.description %>
  </div>

  <div class="listing-content-ratings">
    <h5>Content Allowed</h5>
    <% if @listing.completely_safe? %>
      <p>No NSFW content allowed</p>
    <% else %>
      <ul class="listing-allowed-content">
        <% ["gore", "sexuality", "language", "nudity"].each do |a| %>
          <% if @listing.attributes["nsfw_#{a}"] %>
            <li><%= t(".nsfw_#{a}") %></li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>

  <ul class="image-gallery">
    <% @listing.images.take(20).each do |img| %>
      <li class="image-gallery-item gallery-item-small">
        <%= link_to img do %>
          <%= image_tag img.f(:medium) %>
        <% end %>
      </li>
    <% end %>
  </ul>


  <% if policy(@listing).open? %>
    <% if current_user.stripe_user_id %>
      <div class="listing-confirm flex-row">
        <span>
          This listing is closed, and no new orders can be made.
        </span>
        <%= form_tag open_listing_path(@listing) do %>
          <%= submit_tag("Open Listing", class: "checkmark-submit-button") %>
        <% end %>
      </div>
    <% else %>
      <div class="listing-confirm flex-row">
        <span>
          You need to <%= link_to "add Stripe", authorize_stripe_index_path %>
          before opening a listing
        </span>
      </div>
    <% end %>
  <% elsif policy(@listing).close? %>
    <div class="listing-confirm flex-row">
      <span>
        This listing is open, and accepting new orders
      </span>
      <%= form_tag close_listing_path(@listing) do %>
        <%= submit_tag("Close Listing", class: "cross-delete-button") %>
      <% end %>
    </div>
  <% end %>

  <% if @listing.user != current_user %>
    <%= link_to "Make an Order", 
      new_listing_order_path(@listing),
      :class => "listing-order-button" %>
  <% end %>
</div>