config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "rails/letter_opener"
  end

  mount Apipony::Engine => '/api/documentation'

  mount ActionCable.server => '/cable'

  get "/@:id" => 'users#show'
  patch "/@:id" => "users#update"
  delete "/@:id" => "users#destroy"
  post "/@:id/subscribe" => "users#subscribe"
  delete "/@:id/unsubscribe" => "users#unsubscribe"

  ############
  # CONCERNS #
  ############

  concern :reportable do
    post "report", on: :member
  end

  concern :commentable do
    post :comment, on: :member
    get :comments, on: :member
  end

  concern :replyable do
    resources :replies
  end

  concern :forumable do
    resources :topics do
      concerns :replyable
    end
  end

  ##################
  # RESTFUL ROUTES #
  ##################
  
  resources :favorites, only: [:create, :destroy] do
    get 'includes_image', on: :member
  end

  resources :conversations do
    resources :messages, only: [:index, :new, :create] do
      get 'by_time', on: :collection
    end
    post :read, on: :member
  end

  resources :tags do
    collection do
      get "suggest"
    end
    concerns :forumable
  end

  resources :commissions_dashboard, only: :index
  ##
  # Not really resourceful at all but whatever yolo
  resources :stripe, only: [] do
    collection do
      get :authorize
      get :callback
    end
  end
  
  resources :listings do
    get 'search', on: :collection
    get 'mine', on: :collection
    post 'confirm', on: :member
    post 'open', on: :member
    post 'close', on: :member

    resources :orders do
      post 'confirm', on: :member
      post 'accept', on: :member
      post 'purchase', on: :member
      post 'fill', on: :member
      post 'reject', on: :member
    end
  end

  get "/my_orders", to: "orders#mine"

  resources :tag_group_changes, only: [:show] do
  end

  resources :images do
    member do
      post "created"
    end

    collection do
      get "feed"
    end

    resources :tag_groups do
      resources :changes, only: [:index], controller: :tag_group_changes
    end

    concerns :reportable, :commentable
  end

  devise_for :users,
             path: "accounts",
             controllers: {
               sessions: "users/sessions"
             }

  resources :users, only: [:show, :edit, :update, :index] do
    get 'search', on: :collection
    ##
    # This is done so it's easier to see a users collections.
    # Meanwhile, creation and modification of collections is its own thing.
    member do
      put 'enable_twofactor'
      get 'verify_twofactor'
      get 'backup_twofactor'
      put 'confirm_twofactor'
      put 'disable_twofactor'
      get 'favorites'
      get 'creations'
      post 'subscribe'
      delete 'unsubscribe'
    end
  end

  resources :collections do
    get :mine, on: :collection
    ##
    # OK we get non-REST here
    resources :images, only: [:create, :destroy], controller: :collection_images do
      ##
      # An action which sees if an image already exists in the collection
      get "exists", on: :collection
    end

    resources :curatorships, except: [:index, :show]
    member do
      post "subscribe"
      delete "unsubscribe"
      ##
      # Refactor these out eventually
      post "add"
      delete "remove"
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'unread'
      post 'mark_all_read'
    end

    member do
      post 'read'
    end
  end

  resources :notes do
    collection do
      get 'feed'
    end
    concerns :replyable
  end

  ################
  # ADMIN ROUTES #
  ################

  namespace :admin do
    resources :images, only: [:index, :destroy] do
      post "absolve", on: :member
      collection do
        get 'live'
      end
    end
  end

  #################
  # BROWSE ROUTES #
  #################

  ########################
  # SINGLE ACTION ROUTES #
  ########################
  get 'settings', to: 'users#edit'
  post 'settings', to: 'users#update'

  #################
  # STATIC ROUTES #
  #################
  root to: "frontpage#index"
  get 'about', to: "static_stuff#about"
  get 'people', to: "static_stuff#people"
  get 'guidelines', to: "static_stuff#guidelines"
  get 'contact', to: "static_stuff#contact"
  get 'rules', to: "static_stuff#rules"
  get 'faq', to: "static_stuff#faq"
  get 'help', to: "static_stuff#help"
  get 'press', to: "static_stuff#press"
  get "terms_of_service", to: "static_stuff#terms_of_service"

  get 'search', to: "images#search"
end

app/views/shared/401.html.erb
<h1>You are not allowed to do that</h1>
<%= audio_tag("access_denied.mp3", autoplay: true) %>

app/views/shared/_browse_tabs.html.erb
<nav class="generic-card imagehex-tab-container">
  <div class="imagehex-tabs">
    <%= link_to images_path, class: current(images_path) do %>
      <%= svg "icons/image" %>
      <div><%= t(".images") %></div>
    <% end %>

    <%= link_to collections_path, class: current(collections_path) do %>
      <%= svg "icons/collection" %>
      <div><%=  t(".collections") %></div>
    <% end %> 
    
    <%= link_to users_path, class: current(users_path) do %>
      <%= svg "default-avatar-no-background" %>
      <div><%= t(".creators") %></div>
    <% end %>

    <%= link_to listings_path, class: current(listings_path) do %>
      <%= svg "icons/listings" %>
      <div>Listings</div>
    <% end %>
  </div>
</nav>

app/views/shared/_comment.html.erb
<%# Collection partial for a comment %> 

<%# Anchor for comment links from Notifications. %>
<div class="comment" id="comment-<%= comment.id %>">
  
  <div class="user-comment-avatar">
    <%= link_to comment.user do %>
      <%= image_tag comment.user.avatar_img_thumb %>
    <% end %>
  </div>

  <div class="comment-text">
    <%# Username, with link to user page, and "commented [time value] ago". %>
    <div class="user-comment-info">
      <%= link_to comment.user.name, user_path(comment.user), class: "comment-username" %>
      <%= " " + t(".commented") + " " + time_ago_in_words(comment.created_at) + " " + t(".ago") %>
    </div>
    <p class="comment-reply" data-user-name="<%= comment.user.name %>"><%= t(".reply") %></p>

    <%# Comment body, the text in the comment itself. %>
    <div class="comment-body">
      <%= markdown_parse(comment.body) %>
    </div>
  </div>
  
</div>

app/views/shared/_comments.html.erb
<%# Generic comments partial for use with more than just image pages. %>
<% if comments.empty? %>
  <p class="no-comments"><%= t(".no_comments_yet") %>
<% else %>
  <%= render partial: "shared/comment", collection: comments.for_display %>
<% end %>

app/views/shared/_report_stub.html.erb
<%# Pass in a reportable as a subject and this will make a form to %>
<%# report that subject %>

<p class="tooltip-title"><%= t(".report") %>
<div id="report-form">
  <%= form_tag(url) do %>  
    <p><%= t(".reason_for_report") %>

    <% ImageReport.reasons.each do |k, v| %>
      <div class="report-row">
        <%= radio_button_tag("report[reason]", k) %>
        <%= label "report[reason]", k, k.humanize %>
      </div>
    <% end %>
    
    <p><%= t(".extra_information") %></p>
    <%= text_area_tag "report[message]" %>

    <div class="report-buttons">
      <%= button_tag t(".cancel"), type: :reset, id: "report-cancel-button" %>
      <%= submit_tag t(".report") %>
    </div>
  <% end %>
</div>

app/views/shared/_responsive_image.html.erb
<picture>
  <source
  media="(min-width: 5000px)"
  srcset="<%= img.f :huge %>">
  <source
  media="(min-width: 2500px)"
  srcset="<%= img.f :large %>">
  <source
  media="(min-width: 1500px)"
  srcset="<%= img.f :medium %>">
  <source
  media="(max-width: 750px)"
  srcset="<%= img.f :large %>"
  >
  <%= image_tag(img.f :medium) %>
</picture>