config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do


  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "rails/letter_opener"
  end

  mount Apipony::Engine => '/api/documentation'

  mount ActionCable.server => '/cable'

  get "/@:id" => 'users#show'
  patch "/@:id" => "users#update"
  delete "/@:id" => "users#destroy"
  post "/@:id/subscribe" => "users#subscribe"
  delete "/@:id/unsubscribe" => "users#unsubscribe"

  ############
  # CONCERNS #
  ############

  concern :reportable do
    post "report", on: :member
  end

  concern :commentable do
    post :comment, on: :member
    get :comments, on: :member
  end

  concern :replyable do
    resources :replies
  end

  concern :forumable do
    resources :topics do
      concerns :replyable
    end
  end

  ##################
  # RESTFUL ROUTES #
  ##################
  
  resources :favorites, only: [:create, :destroy] do
    get 'includes_image', on: :member
  end

  resources :conversations do
    resources :messages, only: [:index, :new, :create] do
      get 'by_time', on: :collection
    end
    post :read, on: :member
  end

  resources :tags do
    collection do
      get "suggest"
    end
    concerns :forumable
  end

  resources :commissions_dashboard, only: :index
  ##
  # Not really resourceful at all but whatever yolo
  resources :stripe, only: [] do
    collection do
      get :authorize
      get :callback
    end
  end
  
  resources :listings do
    get 'search', on: :collection
    get 'mine', on: :collection
    post 'confirm', on: :member
    post 'open', on: :member
    post 'close', on: :member

    resources :orders do
      post 'confirm', on: :member
      post 'accept', on: :member
      post 'purchase', on: :member
      post 'fill', on: :member
      post 'reject', on: :member
    end
  end

  get "/my_orders", to: "orders#mine"

  resources :tag_group_changes, only: [:show] do
  end

  resources :images do
    member do
      post "created"
    end

    collection do
      get "feed"
    end

    resources :tag_groups do
      resources :changes, only: [:index], controller: :tag_group_changes
    end

    concerns :reportable, :commentable
  end

  devise_for :users,
             path: "accounts",
             controllers: {
               sessions: "users/sessions"
             }

  resources :users, only: [:show, :edit, :update, :index] do
    get 'search', on: :collection
    ##
    # This is done so it's easier to see a users collections.
    # Meanwhile, creation and modification of collections is its own thing.
    member do
      put 'enable_twofactor'
      get 'verify_twofactor'
      get 'backup_twofactor'
      put 'confirm_twofactor'
      put 'disable_twofactor'
      get 'favorites'
      get 'creations'
      post 'subscribe'
      delete 'unsubscribe'
    end
  end

  resources :collections do
    get :mine, on: :collection
    ##
    # OK we get non-REST here
    resources :images, only: [:create, :destroy], controller: :collection_images do
      ##
      # An action which sees if an image already exists in the collection
      get "exists", on: :collection
    end

    resources :curatorships, except: [:index, :show]
    member do
      post "subscribe"
      delete "unsubscribe"
      ##
      # Refactor these out eventually
      post "add"
      delete "remove"
    end
  end

  resources :notifications, only: [:index] do
    collection do
      get 'unread'
      post 'mark_all_read'
    end

    member do
      post 'read'
    end
  end

  resources :notes do
    collection do
      get 'feed'
    end
    concerns :replyable
  end

  ################
  # ADMIN ROUTES #
  ################

  namespace :admin do
    resources :images, only: [:index, :destroy] do
      post "absolve", on: :member
      collection do
        get 'live'
      end
    end
  end

  #################
  # BROWSE ROUTES #
  #################

  ########################
  # SINGLE ACTION ROUTES #
  ########################
  get 'settings', to: 'users#edit'
  post 'settings', to: 'users#update'

  #################
  # STATIC ROUTES #
  #################
  root to: "frontpage#index"
  get 'about', to: "static_stuff#about"
  get 'people', to: "static_stuff#people"
  get 'guidelines', to: "static_stuff#guidelines"
  get 'contact', to: "static_stuff#contact"
  get 'rules', to: "static_stuff#rules"
  get 'faq', to: "static_stuff#faq"
  get 'help', to: "static_stuff#help"
  get 'press', to: "static_stuff#press"
  get "terms_of_service", to: "static_stuff#terms_of_service"

  get 'search', to: "images#search"
end

app/models/order/group/tag.rb
class Order::Group::Tag < ActiveRecord::Base
  belongs_to :group,
    class_name: "Order::Group",
    foreign_key: :order_group_id,
    inverse_of: :group_tags

  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true
##
# Represents a tag in the ImageHex database.
# Tags must have a unique name, and are not case sensative.
#
# Tags are formatted before saving to remove excess spaces ("do  thing" becomes
# "do thing"), trailing and leading whitespace " do thing " becomes "do thing"),
class Tag < ActiveRecord::Base
  extend FriendlyId
  include Forumable
  friendly_id :name, use: :slugged
  ##
  # CALLBACKS:
  before_validation :fix_name, on: :create
  ##
  # SCOPES
  scope :by_importance, -> { order(importance: :desc) }
  ##
  # ASSOCIATIONS:
  has_many :tag_group_members

  has_many :tag_groups, through: :tag_group_members

  has_many :images, -> { order(created_at: :desc) }, through: :tag_groups

  validates :name, uniqueness: { case_sensative: false }

  validates :importance, inclusion: { in: (0..5) }

  ##
  # Suggest tags beginning with a string.
  # Tags are returned alphabetically.
  # Returns 10 tags at a time.
  # Usage:
  #   Tag.suggest("ha") => ["hack", "halloween"]
  def self.suggest(n)
    query = %Q{
    SELECT tags.name, tags.id, tags.importance  FROM tags
    WHERE tags.name LIKE ?
    ORDER BY importance ASC
    }
    finder = "#{n.delete('%').downcase.strip.squish}%"
    find_by_sql([query, finder])
  end


  def self.for_content(content)
    joins(:images).where(tag_groups: {image: Image.for_content(content)})
  end

  def self.use_relative_model_naming?
    true
  end

  ####################
  # INSTANCE METHODS #
  ####################
  
  def should_generate_new_friendly_id?
    name_changed?
  end

  def often_seen_with
    g = tag_groups
    Tag.joins(tag_group_members: :tag_group)
      .where(tag_groups: { image_id: g.select(:image_id) })
      .where.not(tag_groups: { id: g.select(:id) })
      .group(:id)
      .order("COUNT(*) DESC")
      .select("tags.*, COUNT(*) AS count")
  end

  ##
  # Neighbors provides a list of tags that are commonly used
  # with this tag.
  def neighbors
    Tag.joins(:tag_group_members)
      .where(tag_group_members: { tag_group_id: tag_groups })
      .where.not(id: self)
      .group(:id)
      .order("COUNT(*) DESC")
      .select("tags.*, COUNT(*) AS count")
  end

  private

  ##
  # Callback which formats the name.
  def fix_name
    self.name = name.strip.squish
  end
end

app/models/tag/topic.rb
class Tag::Topic < ApplicationRecord
  extend FriendlyId
  include Replyable

  friendly_id :slug_candidates, use: :slugged

  belongs_to :tag, required: true

  belongs_to :user, required: true

  has_many :replies,
    foreign_key: :tag_topic_id,
    inverse_of: :topic

  def parent_name
    tag.name
  end

  def parent
    tag
  end

  def slug_candidates
    [
      [:created_at, :title],
      [:created_at, :title, :user_id]
    ]
  end

  def self.use_relative_model_naming?
    true
  end
end

app/models/tag/topic/reply.rb
class Tag::Topic::Reply < ApplicationRecord
  belongs_to :topic,
    class_name: "Tag::Topic",
    foreign_key: :tag_topic_id,
    required: true,
    touch: true,
    inverse_of: :replies

  belongs_to :user,
    required: true
end

app/controllers/tags_controller.rb
# frozen_string_literal: true
##
# A single-action controller used for tag suggestion.
class TagsController < ApplicationController
  include TrainTrack
  before_action :ensure_user, only: [:create, :new, :edit, :update]

  ##
  # Given a partial tag name in "params['name']", suggests ten possible
  # completed tags in alphabetical order.
  # Renders a JSON data type.
  def suggest
    if params["name"]
      suggestions = Tag.suggest(params["name"].downcase)
      render json: suggestions
    else
      render status: 422, body: nil
    end
  end

  ##
  # Show a page with info about the tags.
  # @tag:: The tag in question.
  # @neighbors:: Related tags.
  # @images:: Images tagged with the given tag.
  def show
    @tag = Tag.friendly.find(params[:id])
    @neighbors = @tag.neighbors.limit(10)
    @topics = @tag.topics.order(updated_at: :desc)
    @images = @tag.images
      .group("images.id")
      .for_content(content_pref)
      .paginate(page: page, per_page: per_page)
  end

  ##
  # Get a list of all tags.
  # Maybe somebody will find this useful?
  # @tags:: All the tags.
  def index
    @tags = Tag.all
      .for_content(content_pref)
      .paginate(page: page, per_page: per_page)
  end

  ##
  # Create a new tag.
  # @tag:: The tag being created.
  def new
    @tag = Tag.new
  end

  ##
  # Creates a tag.
  # @tag:: The tag being created.
  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        track @tag
        format.html { redirect_to @tag }
        format.json { render 'show' }
      else
        format.html { render 'edit' }
        format.json { render json: @tag.errors, status: :unproccessible_entity }
      end
    end
  end

  ##
  # Edit this tag's description.
  # FIXME: We really should admin-restrict this at some point.
  # @tag:: The tag being edited.
  def edit
    @tag = Tag.friendly.find(params[:id])
  end

  ##
  # Update a tag's description
  # Should be admin-restricted at some point
  def update
    tag = Tag.friendly.find(params[:id])
    track tag
    if tag.update(tag_params)
      track tag
      redirect_to tag
    else
      flash[:warning] = tag.errors.full_messages
      redirect_to action: :edit
    end
  end

  protected

  ##
  # Parameters.
  #
  # Of format:
  #     tag:
  #         description
  def tag_params
    params.require(:tag).permit(:description,
                                :importance,
                                :name)
  end
end

app/views/tags/_discussion.html.erb
<% cache @topics do %>
  <div class="topics-index-outer">
    <div class="topics-index generic-card">
      <div class="topics-onpage-header">
        <h4><%= link_to "Discussion", tag_topics_path(@tag) %></h4>

        <%= link_to new_tag_topic_path(@tag) do %>
          <%= image_tag "icons/add.svg" %>
        <% end %>


      </div>
      <ul class="topic-list">
        <%= render collection: @topics, as: :topic, partial: "topics/topic" %>
      </ul>
    </div>
  </div>
<% end %>

app/views/tags/_form.html.erb
<div class="fields-page-container">
  <%= form_for @tag do |f| %>
    <div class="field-container">
      <%= f.label :name, t(".name"), class: "label input-empty", for: "display-name-field" %>
      <%= f.text_field :name, id: "display-name-field", class: "input" %>
    </div>
    <div class="field-container">
      <%= f.label :importance, class: "lavel input-empty", for: "importance-field" %>
      <%= f.number_field :importance, id: "importance-field", class: "input" %>
    </div>
    <div class="field-container">
      <%= f.label :description, t(".description"), class: "label input-empty", for: "description-text-area" %>
      <%= f.text_area :description, id: "description-text-area", class: "input" %>
    </div>

    <%= f.submit t(".save_changes"), class: "btn-minimal btn-minimal-green btn-right-aligned" %>
  <% end %>
</div>

app/views/tags/_tag.html.erb
<div class="tag-stub generic-card">
  <% cache tag do %>
    <div class="tag-stub-info">
      <h1><%= link_to tag.name, tag %></h1>
      <div class="markdown-area">
        <%= markdown_parse tag.description %>
      </div>
    </div>
  <% end %>
</div>

app/views/tags/edit.html.erb
<%- title t(".editing_tag", tag: @tag.name) %>
<%= render 'form' %> 

app/views/tags/index.html.erb
<div class="tag-index-container">
  <%= render @tags %>
  <%= will_paginate @tags %>
</div>

app/views/tags/show.html.erb
<%- title @tag.name %>

<%= cache @tag, expires_in: 4.hours do %>
  <div class="tag-information">
    <header>
      <h1 class="tag-breadcrumb">
        <%= link_to "Tags", tags_path %>
      </h1>
      <h1><%= @tag.name %></h1>
      <%= link_to t(".edit"), edit_tag_path(@tag), class: "tag-edit-link" %>
    </header>

    <div class="tag-description">
      <%= markdown_parse @tag.description %>
    </div>

    <% unless @neighbors.blank? %>
      <div class="related-tags">
        <h3><%= t(".related_tags") %></h3>
        <ul>
          <% @neighbors.each do |n| %>
            <li class="related-tag">
              <%= link_to n do %>
                <span class="related-tag-name"><%= n.name %></span>
                <span class="related-tag-count">(<%= n.count %>)</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>
<%= render 'discussion' %>

<%= render 'images/show_stub', images: @images %>